Started by user [8mha:////4D2ybD+9yze/lftDsffRCyie6zqs0s51CR0ds/Fr9d61AAAAmR+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyhEgZe/dLi1CL99MTkjMSiSgBFbg+YwgAAAA==[0mG Biswajeet Achary
Running as SYSTEM
[EnvInject] - Loading node environment variables.
Building in workspace /var/jenkins_home/workspace/03-fdc-standard-invoice-report-job
The recommended git tool is: NONE
using credential vinay-github
 > git rev-parse --resolve-git-dir /var/jenkins_home/workspace/03-fdc-standard-invoice-report-job/.git # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/The-Frontdoor-Collective/fdc-etl.git # timeout=10
Fetching upstream changes from https://github.com/The-Frontdoor-Collective/fdc-etl.git
 > git --version # timeout=10
 > git --version # 'git version 2.30.2'
using GIT_ASKPASS to set credentials vinay-github
 > git fetch --tags --force --progress -- https://github.com/The-Frontdoor-Collective/fdc-etl.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/feature/ITDMF-94^{commit} # timeout=10
Checking out Revision 54d2e8fcc5c9ab0ba09fbbbbecb0ac1c544468b3 (refs/remotes/origin/feature/ITDMF-94)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 54d2e8fcc5c9ab0ba09fbbbbecb0ac1c544468b3 # timeout=10
Commit message: "added fix for ITDMF-94"
 > git rev-list --no-walk 54d2e8fcc5c9ab0ba09fbbbbecb0ac1c544468b3 # timeout=10
[03-fdc-standard-invoice-report-job] $ /bin/sh -xe /tmp/jenkins17496176662498193681.sh
+ cd python_scripts
+ [ dev = dev ]
+ python3 Generic_Client_Invoice.py 120
Exception (client): Error reading SSH protocol banner
Traceback (most recent call last):
  File "/var/jenkins_home/.local/lib/python3.9/site-packages/paramiko/transport.py", line 2270, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/var/jenkins_home/.local/lib/python3.9/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/var/jenkins_home/.local/lib/python3.9/site-packages/paramiko/packet.py", line 622, in _read_timeout
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/jenkins_home/.local/lib/python3.9/site-packages/paramiko/transport.py", line 2093, in run
    self._check_banner()
  File "/var/jenkins_home/.local/lib/python3.9/site-packages/paramiko/transport.py", line 2274, in _check_banner
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

/tmp/client_invoice/120/invoice_report/
Traceback (most recent call last):
  File "/var/jenkins_home/.local/lib/python3.9/site-packages/paramiko/transport.py", line 2270, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/var/jenkins_home/.local/lib/python3.9/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/var/jenkins_home/.local/lib/python3.9/site-packages/paramiko/packet.py", line 622, in _read_timeout
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/jenkins_home/workspace/03-fdc-standard-invoice-report-job/python_scripts/get_dell_invoice_custom_report_generation.py", line 40, in <module>
    with pysftp.Connection(host="b2b.sit.veraction.com", username="fcpf_ff_t", password="PecknackCac5", port=8022, cnopts=cnopts) as sftp:
  File "/var/jenkins_home/.local/lib/python3.9/site-packages/pysftp/__init__.py", line 143, in __init__
    self._transport.connect(**self._tconnect)
  File "/var/jenkins_home/.local/lib/python3.9/site-packages/paramiko/transport.py", line 1345, in connect
    self.start_client()
  File "/var/jenkins_home/.local/lib/python3.9/site-packages/paramiko/transport.py", line 698, in start_client
    raise e
  File "/var/jenkins_home/.local/lib/python3.9/site-packages/paramiko/transport.py", line 2093, in run
    self._check_banner()
  File "/var/jenkins_home/.local/lib/python3.9/site-packages/paramiko/transport.py", line 2274, in _check_banner
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
startdate 2022-07-04
enddate 2022-10-25
insert into fdc.client_invoice ( package_id,invoice_date,invoice_amount,invoice_status,client_invoice_number,account_number,status,Facility,PackageTrackingId,ContainerTrackingId,PackageLengthInches,PackageHeightInches,PackageWidthInches,PackageWeightLb,PackageArrivalDate,created_on,package_arrival_date,client_id ) select package_id,invoice_date,Invoice_Amount,invoice_status,client_invoice_number,Account_Number,status,parcel_center_id,PackageTrackingId,ContainerTrackingId,PackageLengthInches,PackageHeightInches,PackageWidthInches,PackageWeightLb,PackageArrivalDate,created_on,package_arrival_date,client_id from fdc_stage.dell_invoice_input where client_id = 120 and date(package_arrival_date)>=(select start_date from fdc.client_fee_agreement where client_id=120) and date(package_arrival_date) <= '2022-10-25'
No of invoices generated :  72
started generating invoice files 
executing  120  customized report script
executing
email has been sent to gbiswajeet.archary@frontdoorcorp.com ...
[Office365connector] Matched status 'SUCCESS' for webhook with name 'null'.
Finished: SUCCESS
